# Generated by Django 3.2.4 on 2021-07-08 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo_consulta', models.IntegerField(choices=[[0, 'Consulta'], [1, 'Sugerencia'], [2, 'Reclamo'], [3, 'Fiado'], [4, 'Felicitaciones']])),
                ('mensaje', models.TextField()),
                ('avisos', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo_barra', models.IntegerField()),
                ('precio_compra', models.IntegerField()),
                ('precio_venta', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('fecha_vencimiento', models.DateField()),
                ('stock', models.IntegerField()),
                ('stock_critico', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.RemoveField(
            model_name='boletadetalle',
            name='numero_boleta',
        ),
        migrations.RemoveField(
            model_name='cuentascorrientes',
            name='rut_cliente',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='Kardex',
        ),
        migrations.RemoveField(
            model_name='ocdetalle',
            name='cod_oc',
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
        migrations.RemoveField(
            model_name='recocdetalle',
            name='cod_oc',
        ),
        migrations.DeleteModel(
            name='UnidadMedida',
        ),
        migrations.AlterModelOptions(
            name='familia',
            options={},
        ),
        migrations.AlterModelOptions(
            name='proveedores',
            options={},
        ),
        migrations.DeleteModel(
            name='BoletaDetalle',
        ),
        migrations.DeleteModel(
            name='Boletas',
        ),
        migrations.DeleteModel(
            name='Clientes',
        ),
        migrations.DeleteModel(
            name='CuentasCorrientes',
        ),
        migrations.DeleteModel(
            name='Oc',
        ),
        migrations.DeleteModel(
            name='OcDetalle',
        ),
        migrations.DeleteModel(
            name='RecOc',
        ),
        migrations.DeleteModel(
            name='RecOcDetalle',
        ),
        migrations.AddField(
            model_name='producto',
            name='familia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.familia'),
        ),
    ]
